# DP: Dynamic Programming

**Recursion**  
A funtion that calls itself

In [4]:
def recur(n):
    print("recur", n)
    recur(n + 1)
    
recur(1)

recur 1
recur 2
recur 3
recur 4
recur 5
recur 6
recur 7
recur 8
recur 9
recur 10
recur 11
recur 12
recur 13
recur 14
recur 15
recur 16
recur 17
recur 18
recur 19
recur 20
recur 21
recur 22
recur 23
recur 24
recur 25
recur 26
recur 27
recur 28
recur 29
recur 30
recur 31
recur 32
recur 33
recur 34
recur 35
recur 36
recur 37
recur 38
recur 39
recur 40
recur 41
recur 42
recur 43
recur 44
recur 45
recur 46
recur 47
recur 48
recur 49
recur 50
recur 51
recur 52
recur 53
recur 54
recur 55
recur 56
recur 57
recur 58
recur 59
recur 60
recur 61
recur 62
recur 63
recur 64
recur 65
recur 66
recur 67
recur 68
recur 69
recur 70
recur 71
recur 72
recur 73
recur 74
recur 75
recur 76
recur 77
recur 78
recur 79
recur 80
recur 81
recur 82
recur 83
recur 84
recur 85
recur 86
recur 87
recur 88
recur 89
recur 90
recur 91
recur 92
recur 93
recur 94
recur 95
recur 96
recur 97
recur 98
recur 99
recur 100
recur 101
recur 102
recur 103
recur 104
recur 105
recur 106
recur 107
recur 108
recur 109
recur 110
recur 11

recur 1503
recur 1504
recur 1505
recur 1506
recur 1507
recur 1508
recur 1509
recur 1510
recur 1511
recur 1512
recur 1513
recur 1514
recur 1515
recur 1516
recur 1517
recur 1518
recur 1519
recur 1520
recur 1521
recur 1522
recur 1523
recur 1524
recur 1525
recur 1526
recur 1527
recur 1528
recur 1529
recur 1530
recur 1531
recur 1532
recur 1533
recur 1534
recur 1535
recur 1536
recur 1537
recur 1538
recur 1539
recur 1540
recur 1541
recur 1542
recur 1543
recur 1544
recur 1545
recur 1546
recur 1547
recur 1548
recur 1549
recur 1550
recur 1551
recur 1552
recur 1553
recur 1554
recur 1555
recur 1556
recur 1557
recur 1558
recur 1559
recur 1560
recur 1561
recur 1562
recur 1563
recur 1564
recur 1565
recur 1566
recur 1567
recur 1568
recur 1569
recur 1570
recur 1571
recur 1572
recur 1573
recur 1574
recur 1575
recur 1576
recur 1577
recur 1578
recur 1579
recur 1580
recur 1581
recur 1582
recur 1583
recur 1584
recur 1585
recur 1586
recur 1587
recur 1588
recur 1589
recur 1590
recur 1591
recur 1592
recur 1593

recur 2899
recur 2900
recur 2901
recur 2902
recur 2903
recur 2904
recur 2905
recur 2906
recur 2907
recur 2908
recur 2909
recur 2910
recur 2911
recur 2912
recur 2913
recur 2914
recur 2915
recur 2916
recur 2917
recur 2918
recur 2919
recur 2920
recur 2921
recur 2922
recur 2923
recur 2924
recur 2925
recur 2926
recur 2927
recur 2928
recur 2929
recur 2930
recur 2931
recur 2932
recur 2933
recur 2934
recur 2935
recur 2936
recur 2937
recur 2938
recur 2939
recur 2940
recur 2941
recur 2942
recur 2943
recur 2944
recur 2945
recur 2946
recur 2947
recur 2948
recur 2949
recur 2950
recur 2951
recur 2952
recur 2953
recur 2954
recur 2955
recur 2956
recur 2957
recur 2958
recur 2959
recur 2960
recur 2961
recur 2962
recur 2963
recur 2964
recur 2965
recur 2966
recur 2967


RecursionError: maximum recursion depth exceeded while calling a Python object

In [6]:
def recur(n):
    if n <= 0:
        return 0
    return recur(n-1) + recur(n-2) + 1

print(recur(3))


4


In [9]:
def f(data):
    print(data)
    return 0
    
def caller():
    r = f("a") 
    r += f("b")
    r += f("c")
    
caller()

a
b
c


**0 1 1 2 3 5 8 13...**
1st 0
2nd 1
3rd = 1st + 2nd = 0 + 1 = 1
4th = 2nd + 3rd = 1 + 1 = 2
5th = 3rd + 4th = 1 + 2 = 3
.....
nth = (n-1)th + (n-2)th  # recurrence relation

**C#**
```C#
public static int Fib(int n)
    {
        if (n <= 1)
        {
            return n;
        }
        else
        {
            return Fib(n - 1) + Fib(n - 2);
        }
    }
```

**C++**
```c++
int f(int n)
{
if (n<=1 )
   return n;
return f(n-1)+f(n-2);
}
```

**Swift**
```Swift
func fibonacciSequence (n: Int) -> [Int]  {
    var fibonacciArray = [Int]()

    for n in 0 ... n {

        if n == 0 {
            fibonacciArray.append(0)
        }
        else if n == 1 {
            fibonacciArray.append(1)
        }
        else {
            fibonacciArray.append (fibonacciArray[n-1] + fibonacciArray[n-2] )
        }
    }
    return fibonacciArray
}

```

**Java**
```Java
int f[]=new int[n+1];
int f[0]=0
int f[1]=1;

for(int i=2;i<=n;i++)
{
    f[i]=f[i-1]+f[i-2];
}

return f[n];
```

**Python**
```Python
def fib(n):
    a = 0
    b = 1
    r = 0
    for _ in range(n):
        r = a
        c = a + b
        a = b
        b = c
        
    return r
```

0 1 1 2 3 5


In [32]:
# Recursive
# TC: O(2^n)
# SC: O(n)

import functools

@functools.lru_cache
def fib(n):
    if n <= 0:
        raise ValueError("n must be >= 1")
    if n == 1:
        return 0
    if n == 2:
        return 1
    
    return fib(n-1) + fib(n-2)

    
print(fib(1), fib(2), fib(3), fib(4), fib(5), fib(6))
# fib(0)
#fib(100)

0 1 1 2 3 5


218922995834555169026

In [25]:
# Recursive
# TC: O(n)
# SC: O(n)

# 1000L -> N/s

# 1L
# 2L

cache = {1:0, 2:1} # dict/Hashmap

def fib(n):
    if n <= 0:
        raise ValueError("n must be >= 1")
    
    if n in cache:
        return cache[n]
    
    res = fib(n-1) + fib(n-2)
    cache[n] = res
    return res
    
print(fib(1), fib(2), fib(3), fib(4), fib(5), fib(6))
# fib(0)
fib(100)

0 1 1 2 3 5


218922995834555169026

In [28]:
def fib(n):
    cache = {1:0, 2:1} # dict/Hashmap
    return fib_util(n, cache)

def fib_util(n, cache):
    if n <= 0:
        raise ValueError("n must be >= 1")
    
    if n in cache:
        return cache[n]
    
    res = fib_util(n-1, cache) + fib_util(n-2, cache)
    cache[n] = res
    return res
    
print(fib(1), fib(2), fib(3), fib(4), fib(5), fib(6))

0 1 1 2 3 5


In [30]:
def fib(n):
    cache = [-1 for _ in range(n+1)]
    return fib_util(n, cache)

# - 0 1 1 2 3 5....
# 0 1 2 3 4 5 6....

def fib_util(n, cache):
    if n <= 0:
        raise ValueError("n must be >= 1")
    
    if n == 1:
        return 0
    if n == 2:
        return 1
    
    if cache[n] != -1:
        return cache[n]
    
    res = fib_util(n-1, cache) + fib_util(n-2, cache)
    cache[n] = res
    return res
    
print(fib(1), fib(2), fib(3), fib(4), fib(5), fib(6))



0 1 1 2 3 5



```
TC:O(n)
SC:O(n)
int f[]=new int[n+1];
int f[0]=0
int f[1]=1;

for(int i=2;i<=n;i++)
{
    f[i]=f[i-1]+f[i-2];
}

return f[n];
```

**TC: O(N)**  
**SC: O(1)**
```Python
def fib(n):
    a = 0
    b = 1
    r = 0
    for _ in range(n):
        r = a
        c = a + b
        a = b
        b = c
        
    return r

print(fib(1), fib(2), fib(3), fib(4), fib(5), fib(6))
```

- Top-Down (Recursion, Memoization) # Start N , end N
- Bottom-Up (Loops, Tabulation) # Start 0, End N

In [ ]:
Recursion
- Backtracking
- DP


Max steps to reach top in size 1,2: Climbing stairs 
    https://leetcode.com/problems/climbing-stairs/
        
        
N=3
1/2

Do I need the actual permutations ?
[1 1 1]
[1 2]
[2 1]

Yes:
    Backtracking
No:
    Count: DP

N=4
[1 1 1 1]
[1 1 2]
[1 2 1]
[2 1 1]
[2 2]

**JAVA**  
```Java
// TC: O(2^N)
// SC: O(N)
public static int backrec(int n)
  { 
    if(n==1)
      return 1;
    
    if(n==2)
      return 2;
    
    return backrec(n-1)+backrec(n-2);
  }
```

**Python**  
```Python

# TC: O(N)
# SC: O(N)
class Solution:
    def climbStairs(self, n: int) -> int:
        arr = {0:1,1:2}
        for i in range(1,n):
            arr[i+1] = arr[i]+arr[i-1]
        return arr[n-1]
```

**Javascript**  
```Javascript
// TC: O(N)
// SC: O(N)

var climbStairs = function(n,map = {}) {
    if(n === 1) {
        return 1;
    } else if(n === 2) {
        return 2;
    }
    
    if(!map[n]) {
        map[n] = climbStairs(n-1, map) + climbStairs(n-2, map);
    }  
    return map[n];
};
```

```
DP-problem
- Look for keywords: min/max, count, unique, ways etc
- Think of a recurrence relation (draw on paper / board)
- Figure out base conditions
- Figure out number of state variables (the variables on which answer depends: 1D, 2D, .....)
- Write a top-down / bottom-up code

DP problem top-down structure
- populate a (cache)/ (dp array/matrix or whatever)
- call utility function with cache

- Write a recursive utility function
    // base conditions
    // cache lookup
    // recursion
    // caching
   

DP problem bottom-up structure
- populate the cache with solution for the trivial cases
- run loops which start from non-trivial cases
      - use recurrene relation to determine solution at current structure
- return last answer
```

**Unique Paths**  
https://leetcode.com/problems/unique-paths/
   
**Python**
```Python
# TC: O(m*n)
# SC: O(m*n)
class Solution:
    def uniquePaths(self, m: int, n: int) -> int:
        path_cache = {}
        def solve(i,j):
            if (i,j) in path_cache:
                return path_cache[(i,j)]
            if i>m-1 or j>n-1:
                return 0
            if i==m-1 and j==n-1:
                return 1
            

            path_cache[(i,j)] = solve(i+1,j) +  solve(i,j+1)
            return ll+rr
        
        return solve(0,0)


class Solution:
    def uniquePaths(self, m: int, n: int) -> int:
        dp = [[0]*n]*m
        dp[0][0] = 1
        for i in range(m):
            for j in range(n):
                if i == 0 or j == 0:
                    dp[i][j] = 1
                else:
                    dp[i][j] = dp[i-1][j] + dp[i][j-1]
        return dp[m-1][n-1]
```

```Python
class Solution:
    def uniquePaths(self, m: int, n: int) -> int:
        d=[[ 0 for _ in range(n)] for _ in range(m)]

        for i in range(m):
            d[i][0] = 1
        
        for i in range(n):
            d[0][i] = 1

        for i in range(1,m):
            for j in range(1,n):
                d[i][j] = d[i-1][j] + d[i][j-1]
        

        return(d[m-1][n-1])
```


```C++
class Solution {
public:
    int uniquePaths(int m, int n) {
        vector<vector<int>> paths(m,vector<int>(n,0));
        for(int i=0;i<m;i++){
            paths[i][0]=1;
        }
        
        for(int j=0;j<n;j++){
            paths[0][j]=1;
        }
        
        for(int i=1;i<m;i++){
            for(int j=1;j<n;j++){
                paths[i][j]=paths[i-1][j] + paths[i][j-1];
            }
        }
        
        return paths[m-1][n-1];
    }
};

```


```JAVA
#JAVA
class Solution {
    public int uniquePaths(int m, int n) {
      int[][] grid = new int[m][n];
    
        for(int i=0;i<m;i++){
            for(int j=0;j<n;j++){
                if(i==0 || j == 0)grid[i][j] =1;
                else
                 grid[i][j] = grid[i-1][j]+grid[i][j-1];
            }
        }
    return grid[m-1][n-1];
    }
   
}

```

In [ ]:
class Solution {
public:
    int cnt=0;
    int uniquePathsutil(int m, int n, int i, int j) {
        if(i>=m || j>=n)
          return 0;
        if(i==m-1 && j==n-1)
        {
            cnt++;
        }

        uniquePathsutil(m,n,i+1, j);
        uniquePathsutil(m,n,i, j+1);
        return cnt;
    }
    
    int uniquePaths(int m, int n) {
       return uniquePathsutil(m,n,0,0);
    }
};


In [ ]:
https://leetcode.com/problems/minimum-path-sum/